### ISSUE TITLE
why is drawSymbols in qwtPlotCurve commented out?

### ISSUE THREAD

**Issue by twillis449** [GauiStori/PyQt-Qwt#10]
In sip/qwt_plot_curve.sip you have commented out the drawSymbols function (lines 238 to 240). Why is that? I make use of drawSymbols in one of my test programs and could not figure out why i could call it in the earlier PyQwt 5.2 and not in your version (!) until I looked at your sip code. 

This issue is not that critical as I don't appear to be using the function anywhere in production code but just in a test program I wrote.

Thanks

Tony

**Comment by GauiStori** [comment]
Hi Tony

Sorry. In the beginning I commented out the ones that didn't work but the
wrapper compiles perfectly with the drawSymbols function.

Thanks. I will uncomment it ASAP and test tonight.

Regards
Gudjon

**Comment by GauiStori** [comment]
Hi Tony

Your issue should be fixed with the last commit.

Regards
Gudjon
