### ISSUE TITLE
complize error

### ISSUE THREAD

**Issue by wdram** [GauiStori/PyQt-Qwt#13]
Configuring Qwt 6.1.2...
Qwt 6.1.3 is being used.
The Qwt .sip files will be installed in /usr/share/sip/PyQt5.
Qwt will be installed in /usr/lib/python3/dist-packages/PyQt5.
PyQt 5.15.0 is being used.
Qt 5.15.0 is being used.
sip 5.3.0 is being used.
The sip executable is /home/allen/.local/bin/sip5.
Qwt is being built with 'protected' redefined as 'public'.
The PEP 484 stubs will be installed in /usr/lib/python3/dist-packages/PyQt5.
Generating the C++ source for the Qwt module...
Error: Unable to create the C++ code.

**Comment by GauiStori** [comment]
Hi

Please take a look at the sip5 branch. I am working on sip5
compatibility. Please let me know if it doesn't work.´

Regards
Gudjon

**Comment by ae92736** [comment]
Hi
i am facing the same issue, there is one difference to take in mind that i am using sip 4.19.7.
when i used the --verbose option this additional information printed.

 /usr/bin/sip -I /home/aye/qwt/PyQt-Qwt/sip -I /usr/share/sip/PyQt5 -n PyQt5.sip -t Qt_5_15_0 -t WS_X11 -B Qt_6_0_0 -y Qwt.pyi -a Qwt.api -P -o -c /home/aye/qwt/PyQt-Qwt/Qwt /home/aye/qwt/PyQt-Qwt/sip/Qwt_Qt5.sip
sip: Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D] [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r] [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file] [@file] [file]
Error: Unable to create the C++ code.

i think sip doesn't allow -n option.
please let me know if you had solved the issue.

**Comment by GauiStori** [comment]
Hi

Sorry for a late answer.
On Wednesday, 3 February 2021 05:58:44 CET ae92736 wrote:
> Hi
> i am facing the same issue, there is one difference to take in mind that i
> am using sip 4.19.7. when i used the --verbose option this additional
> information printed.
> 
>  /usr/bin/sip -I /home/aye/qwt/PyQt-Qwt/sip -I /usr/share/sip/PyQt5 -n
> PyQt5.sip -t Qt_5_15_0 -t WS_X11 -B Qt_6_0_0 -y Qwt.pyi -a Qwt.api -P -o -c
> /home/aye/qwt/PyQt-Qwt/Qwt /home/aye/qwt/PyQt-Qwt/sip/Qwt_Qt5.sip sip:
> Usage: sip [-h] [-V] [-a file] [-b file] [-B tag] [-c dir] [-d file] [-D]
> [-e] [-f] [-g] [-I dir] [-j #] [-k] [-m file] [-o] [-p module] [-P] [-r]
> [-s suffix] [-t tag] [-w] [-x feature] [-X id:file] [-y file] [-z file]
> [@file] [file] Error: Unable to create the C++ code.
> 
> i think sip doesn't allow -n option.
> please let me know if you had solved the issue.

Please try again with the --pyqt-sipdir parameter set.

It compiles on my Debian system with both sip-build and configure.py. 
I tested with sip 4.19.24.

I fixed the generation of Qwt.api this morning so please use the latest
commit.

Hope this helps
Gudjon
