### ISSUE TITLE
Error: No module named qwt_*

### ISSUE THREAD

**Issue by grafoteka** [GauiStori/PyQt-Qwt#15]
Hello, 
I have installed the repository correctly, under Ubuntu 20.04 and with Qt5. But I still having the same error: 

`ModuleNotFoundError: No module named 'qwt_thermo'`

And the same for any qwt module. 

How can I check if everything is correct?

Thank you.

Kinds regards

**Comment by GauiStori** [comment]
Hi Jorge

On Thursday, 17 December 2020 12:11:32 CET Jorge De León Rivas wrote:
> Hello,
> I have installed the repository correctly, under Ubuntu 20.04 and with Qt5.
> But I still having the same error:
> `ModuleNotFoundError: No module named 'qwt_thermo'`
> And the same for any qwt module.
> How can I check if everything is correct?

Please take a look at the qt5examples directory all the example should work 
and many include QwtThermo.

>>>from PyQt5 import Qwt

>>>Qwt.QwtThermo
<class 'Qwt.QwtThermo'>

The Debian package will be updated soon.

Hope this helps
Gudjon
