### ISSUE TITLE
Compile error 

### ISSUE THREAD

**Issue by tt418232417** [GauiStori/PyQt-Qwt#17]
Traceback (most recent call last):
  File "/Users/roy/Downloads/PyQt-Qwt-1.02.02/mk_distinfo.py", line 112, in <module>
    fn_f = open(fn, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Users/roy/opt/anaconda3/qwt/api/python/Qwt.api'
make: *** [install_distinfo] Error 1

**Comment by GauiStori** [comment]
Hi

Please take a look at commit:
1ce15d556b81c1c7504420cea20f568d02d60797

The .api file is generated now when using the configure.py script but 
I have not fixed generation with sip-build.

Regards
Gudjon
