### ISSUE TITLE
zoomStack and setZoomStack calls are missing

### ISSUE THREAD

**Issue by razman786** [GauiStori/PyQt-Qwt#18]
Firstly, thank you for this awesome work for getting Qwt6 working with PyQt5!

I noticed that zoomStack and setZoomStack calls are missing. I can see the following in the respective sip file: 
```
//const QStack<QRectF> &zoomStack() const; FIXME
//void setZoomStack( const QStack<QRectF> &, int zoomRectIndex = -1 ); FIXME
```

Are there any plans to get this included, or is there a known workaround?

Any help would be very much appreciated.

**Comment by GauiStori** [comment]
Hi

On Friday, 9 April 2021 17:36:47 CEST Raz wrote:
> Firstly, thank you for this awesome work for getting Qwt6 working with
> PyQt5!
Thanks
> 
> I noticed that zoomStack and setZoomStack calls are missing. I can see the
> following in the respective sip file: ```
> //const QStack<QRectF> &zoomStack() const; FIXME
> //void setZoomStack( const QStack<QRectF> &, int zoomRectIndex = -1 ); FIXME
> ```
> 
> Are there any plans to get this included, or is there a known workaround?
Hihi, yes, now there is :)
> 
> Any help would be very much appreciated.
I don't see any reference to QStack in PyQt5. I will ask a question on the 
PyQt mailing list and keep you informed.

Regards
Gudjon

**Comment by GauiStori** [comment]
Hi again

Please check the branch zoomstack. I have not tested it yet but it might
work.

Regards
Gudjon

**Comment by razman786** [comment]
Hi

Thank you for the super fast response! I will give the branch a run through and let you know how it goes!

Cheers,
Raz

**Comment by razman786** [comment]
Hi Gudjon

I've created a pull request here https://github.com/GauiStori/PyQt-Qwt/pull/19 with a quick hack on the issue. So far it gets `setZoomStack()` working, but `zoomStack()` still gives errors - details are in the pull request.

Cheers,
Raz

**Comment by GauiStori** [comment]
Hi Raz

This should be fixed now and I have merged the zoomstack branch into next_version.

Cheers
Gudjon

**Comment by razman786** [comment]
Hi Gudjon

I've tested the updated next_version branch and it is working like a charm! Thank you!

Cheers,
Raz
