### ISSUE TITLE
Compatibility with sip <= 4.19.8

### ISSUE THREAD

**Issue by otonck** [GauiStori/PyQt-Qwt#6]
Hi Gudjon, and thanks again for your work on issue #4 

here is another questionning we have with PyQt-Qwt :

since the latest sip version released on PIPY is sip 4.19.8, it would be convenient for us that PyQt-Qwt compiles with this version. The need for sip >= 4.19.11 seems to complexify the deployment of packages using PyQt-Qwt, and I'm not sure about the reason of this requirement.

Moreover, if you plan to publish one day the PyQt-Qwt on PIPY, I think it will be easier with a sip version available on PIPY.

I tried to compile and quickly test PyQt-Qwt with sip 4.19.8, and just had to remove the sip -n ([new in sip 4.19.9](http://pyqt.sourceforge.net/Docs/sip4/command_line.html#cmdoption-sip-n)) argument in the configure.py script to make it work.

In my opinion, a good change in the configure script for PyQt-Qwt would be to replace this line :

`    argv.append('-n sip')`

by this :

```
    # -n arg new in sip 4.19.9
    if target_config.sip_version >= version_from_string("4.19.9"):
        argv.append('-n sip')
```

What do you think about this ? I can prepare a pullrequest if you like.

Thanks again,

Regards,

Olivier

**Comment by GauiStori** [comment]
Hi Oliver

> 
> Moreover, if you plan to publish one day the PyQt-Qwt on PIPY, I think it will be easier with a sip version available on PIPY.
I am very interested and I have started looking into it but it may take time.
> 
> I tried to compile and quickly test PyQt-Qwt with sip 4.19.8, and just had to remove the sip -n ([new in sip 4.19.9](http://pyqt.sourceforge.net/Docs/sip4/command_line.html#cmdoption-sip-n)) argument in the configure.py script to make it work.
> 
> In my opinion, a good change in the configure script for PyQt-Qwt would be to replace this line :
> 
> `    argv.append('-n sip')`
> 
> by this :
> 
> ```
>     # -n arg new in sip 4.19.9
>     if target_config.sip_version >= version_from_string("4.19.9"):
>         argv.append('-n sip')
> ``` 
> What do you think about this ? I can prepare a pullrequest if you like.
Thanks. I was about to fix this for making backporting in Debian easier.
Will fix today.

Regards
Gudjon
