### ISSUE TITLE
QwtLog10ScaleEngine wraper needed

### ISSUE THREAD

**Issue by twillis449** [GauiStori/PyQt-Qwt#9]
Hi 

I have a huge code base that makes use of the last PyQwt wrapper that Gerard Vermeulen made for the old Python 4 / Qwt 4 stuff. I'm now faced with the task of porting the code base to Python 3 / qt 5 / Qwt 6 etc. One of the axis scale functions i need is QwtLog10ScaleEngine. It looks like you have not yet included that in your distribution and I'd be grateful if you could add it.

Thanks

Tony

**Comment by GauiStori** [comment]
Hi Tony

> I have a huge code base that makes use of the last PyQwt wrapper that Gerard Vermeulen made for the old Python 4 / Qwt 4 stuff. 
> I'm now faced with the task of porting the code base to Python 3 / qt 5 / Qwt 6 etc. One of the axis scale functions i need is QwtLog10ScaleEngine. 
Great. Please let me know how it works.

> It looks like you have not yet included that in your distribution and I'd be grateful if you could add it.
I'm pretty sure the function has been renamed to QwtLogScaleEngine. Please take a look at the 
examples bode.py and controls.py.
https://qwt.sourceforge.io/class_qwt_log_scale_engine.html

Regards
Gudjon

**Comment by twillis449** [comment]
Thank-you for the reply. Yes, you are correct. Looks like  QwtLog10ScaleEngine has disappeared from Qwt. I will use QwtLogScaleEngine.
